### ISSUE TITLE
.net core compatible release

### ISSUE THREAD

**Issue by atiq-cs** [devlead/Devlead.Statiq#1]
Hi,
I am trying to use this package with .net core sdk project and I am having trouble.

Is it possible to release a .net core compatible version?

Thanks so much.

**Comment by devlead** [comment]
Version 0.12. now has .NET Core 3.1 support in addition to .NET 5.
<img width="271" alt="image" src="https://user-images.githubusercontent.com/1647294/128731520-8e9d52ad-8d03-482e-9820-9a2838b72303.png">

https://www.nuget.org/packages/Devlead.Statiq/0.12.0

**Comment by atiq-cs** [comment]
Very nice, kudos!
