### ISSUE TITLE
Statiq.Web upgrade to 1.0.0-beta.44 seems breaking

### ISSUE THREAD

**Issue by henrikrxn** [devlead/Devlead.Statiq#3]
I use Devlead.Statiq in my blog because I have made some modifications to the Cleanblog theme in a fork and your library is a very easy way to use that fork, so thanks for the idea and implementation.

I tried to update my blog to the latest Statiq.Web (1.0.0-beta.44) and ran into some problems.
My guess is that the problem started with Statiq.Web 1.0.0-beta.38 which included a version of Statiq.Framework that made a number of breaking changes that affected Devlead.Statiq

I forked Devlead.Statiq and made a branch where I tried to isolate the problem by adding a project that only uses the theme functionality. The main reason I did this was that I had problems running the existing test project because of a file getting locked, so you might also need to fix some stuff for the tabgroup functionality

https://github.com/henrikrxn/Devlead.Statiq/tree/Update-to-Statiq-Web-1-0-0-beta-44
Did not think it was worth doing a PR at this point.

The branch fixes the compile errors introduced by the breaking changes from Statiq.*
That could of course be the source of the problems, but I do not think so.

I tried to investigate on the simple repro, but my knowledge about the inner workings of Statiq  is not sufficient to understand and fix the problem and make a PR.

When I run the `DevLead.Statiq.TestThemes` project I added this way:

`dotnet run --framework net6.0 -- preview --clean-mode Full --Verbose`

 I get the following errors as part of the verbose output

```
[INFO] [Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager] User profile is available. Using 'C:\Users\Henrik\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
[ERRO] Content/PostProcess » RenderContentPostProcessTemplates » ExecuteIf » ExecuteIf » ExecuteIf » ExecuteConfig » RenderRazor » [E:/MyGithub/Devlead.Statiq/src/DevLead.Statiq.TestThemes/input/posts/HelloWorld.md => posts/helloworld.html] The layout view '/_layout.cshtml' could not be located. The following locations were searched:
/_layout.cshtml
[INFO] ========== Execution Summary ==========
```

and later a "follow-up"

```
[INFO] - Analyzer Before Engine Execution Events in 1 ms
[INFO] - Engine Execution in 3150 ms
[CRIT] The layout view '/_layout.cshtml' could not be located. The following locations were searched:
/_layout.cshtml
[INFO] To get more detailed logging output run with the "-l Debug" flag
```

After this when put a comment `//` in `DevLead.Statiq.TestThemes\Program.cs` at the beginning of the `.AddThemeFromUri` line then things build just fine (provided the theme folder has content)
That is why I think the breaking Statiq.Framework changes affected, at least, the theme part of your library.

**Comment by devlead** [comment]
Fixed by #4
