### ISSUE TITLE
Update to Statiq.Web v1.0.0-beta.49 / Statiq.Framework v1.0.0-beta.62

### ISSUE THREAD

**Issue by rdeago** [devlead/Devlead.Statiq#4]
## Problem

Since [Statiq.Framework 1.0.0-beta.53](https://github.com/statiqdev/Statiq.Framework/releases/tag/v1.0.0-beta.53), the type of the `IEngine.FileSystem` property has changed from `IFileSystem` to `IReadOnlyFileSystem`.

This causes a "Method not found" error in lambdas passed to `Bootstrapper.ConfigureEngine`, as soon as the `IEngine.FileSystem` property is referenced, if said lambdas were compiled against a previous version of `Statiq.Framework`.

Because of this change, `Devlead.Statiq` v0.14.0 (which, as luck would have it, was built against `Statiq.Framework` v1.0.0-beta.52) breaks in three different places, in classes [TabGroupExtensions](https://github.com/devlead/Devlead.Statiq/blob/0.14.0/src/Devlead.Statiq/Tabs/TabGroupExtensions.cs#L29), [UriThemeExtensions](https://github.com/devlead/Devlead.Statiq/blob/0.14.0/src/Devlead.Statiq/Themes/UriThemeExtensions.cs#L21) , and [MarkdownExtensions](https://github.com/devlead/Devlead.Statiq/blob/0.14.0/src/Devlead.Statiq/Markdown/MarkdownExtensions.cs#L63) respectively.

## Solution

There do not seem to be other breaking changes, in either `Statiq.Framework` or `Statiq.Web`, impacting `Devlead.Statiq`.

Therefore, a dependency update followed by a rebuild should suffice as a fix for this issue.

## Final considerations

While waiting for an update to Devlead.Statiq, I have copied `UriThemeExtensions` in my blog's project, with proper attribution of course, and it compiles.

Thanks a lot @devlead!

---

**EDIT:**

I forked this repository and gave a shot at a simple dependency update + rebuild.

Turns out a couple code changes are necessary, due to `MarkdownHelper.RenderMarkdown` now having two more parameters.

Besides, `AddThemeFromUri` cannot use `Bootstrapper.ConfigureEngine` any longer, because once the engine is created, changes to the file system are ignored. `Bootstrapper.ConfigureFileSystem` is the correct method to use from `Statiq.Framework` v1.0.0-beta.53 onwards. The only drawback is the lack of `CreateHttpClient`, but that's literally 4 lines that can well be copypasted as it's just pretty standard initialization code.

PR incoming.

**Comment by devlead** [comment]
Verssion 0.15.0 is now out
https://www.nuget.org/packages/Devlead.Statiq/0.15.0
